export const COINS = [
	{ id: 'RUB', name: 'RUB', code: 'RU', title: 'Россия' },
	{ id: 'USD', name: 'USD', code: 'US', title: 'США' },
	{ id: 'EUR', name: 'EUR', code: 'EU', title: 'Европа' },
	{ id: 'GBP', name: 'GBP', code: 'GB', title: 'Великобритания' },
	{ id: 'AUD', name: 'AUD', code: 'AU', title: 'Австралия' },
	{ id: 'AZN', name: 'AZN', code: 'AZ', title: 'Азербайджан' },
	{ id: 'CAD', name: 'CAD', code: 'CA', title: 'Канада' },
	{ id: 'CHF', name: 'CHF', code: 'CH', title: 'Швейцария' },
	{ id: 'CNY', name: 'CNY', code: 'CN', title: 'Китай' },
	{ id: 'JPY', name: 'JPY', code: 'JP', title: 'Япония' },
	{ id: 'INR', name: 'INR', code: 'IN', title: 'Индия' },
	{ id: 'ZAR', name: 'ZAR', code: 'ZA', title: 'Южно-Африканская Республика' },
	{ id: 'SEK', name: 'SEK', code: 'SE', title: 'Швеция' },
	{ id: 'NOK', name: 'NOK', code: 'NO', title: 'Норвегия' },
	{ id: 'HKD', name: 'HKD', code: 'HK', title: 'Гонконг' },
	{ id: 'SGD', name: 'SGD', code: 'SG', title: 'Сингапур' },
	{ id: 'KRW', name: 'KRW', code: 'KR', title: 'Южная Корея' },
	{ id: 'BRL', name: 'BRL', code: 'BR', title: 'Бразилия' },
	{ id: 'TRY', name: 'TRY', code: 'TR', title: 'Турция' },
	{ id: 'IDR', name: 'IDR', code: 'ID', title: 'Индонезия' },
	{ id: 'DKK', name: 'DKK', code: 'DK', title: 'Дания' },
	{ id: 'PLN', name: 'PLN', code: 'PL', title: 'Польша' },
	{ id: 'THB', name: 'THB', code: 'TH', title: 'Таиланд' },
	{ id: 'AED', name: 'AED', code: 'AE', title: 'ОАЭ' },
]
